# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant::Config.run do |config|
Vagrant.configure("2") do | config |

  # TeamCity build agent - Ubuntu
  config.vm.define :agent91 do | config |
    config.vm.box = "lucid32"
    config.vm.box_url = "http://files.vagrantup.com/lucid32.box"
    #config.vm.box = "lucid64"
    #config.vm.box_url = "http://files.vagrantup.com/lucid64.box"
    config.vm.hostname = "agent91.local"
    #config.vm.forward_port 80, 8080
    config.vm.network :forwarded_port, guest: 9090, host: 9090
    config.vm.network :private_network, ip: "192.168.33.11"
    #config.vm.network :public_network

    config.vm.provider :virtualbox do | vbox |
      vbox.customize ["modifyvm", :id, "--memory", 512]
      vbox.customize ["modifyvm", :id, "--name", "agent91"]
    end

    config.vm.provision :puppet do |puppet|
      puppet.module_path = "../modules"
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "agent.pp"
      puppet.options = ["--verbose", "--debug"]
    end
  end

  # TeamCity build agent - CentOS
  config.vm.define :agent92 do | config |
    config.vm.box = "CentOS-6.3-x64"
    #config.vm.box_url = ""
    config.vm.hostname = "agent92.local"
    #config.vm.forward_port 80, 8080
    config.vm.network :forwarded_port, guest: 9090, host: 9090
    config.vm.network :private_network, ip: "192.168.33.11"

    config.vm.provider :virtualbox do | vbox |
      vbox.customize ["modifyvm", :id, "--memory", 512]
      vbox.customize ["modifyvm", :id, "--name", "agent92"]
    end

    config.vm.provision :puppet do |puppet|
      puppet.module_path = "../modules"
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "agent.pp"
      puppet.options = ["--verbose", "--debug"]
    end
  end
end
